name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download pic from gravatar 
        run: wget https://www.gravatar.com/avatar/${{ secrets.GRAVATAR_HASH }}.jpeg?s=400 -O jorgemontes.jpeg
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Twenty-Seconds_cv.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Twenty-Seconds_cv.pdf

          
      
      
      
    
